export const CATEGORIES = [
  'all',
  'antiques',
  'appliances',
  'arts+crafts',
  'atvs/utvs/snow',
  'auto parts',
  'auto wheels & tires',
  'aviation',
  'baby+kids',
  'barter',
  'beauty+hlth',
  'bike parts',
  'bikes',
  'boat parts',
  'boats',
  'books',
  'business',
  'cars+trucks',
  'cds/dvd/vhs',
  'cell phones',
  'clothes+acc',
  'collectibles',
  'computer parts',
  'computers',
  'electronics',
  'farm+garden',
  'free stuff',
  'furniture',
  'garage sales',
  'general',
  'heavy equipment',
  'household',
  'jewelry',
  'materials',
  'motorcycle parts',
  'motorcycles',
  'music instr',
  'photo+video',
  'RVs',
  'sporting',
  'tickets',
  'tools',
  'toys+games',
  'trailers',
  'video gaming',
];

export const OWNER_TYPE = {
  ALL: 'All',
  OWNER: 'Owner',
  DEALER: 'Dealer',
};
