export const CATEGORIES = [
  'all',
  //   'antiques',
  'appliances',
  //   'arts+crafts',
  //   'atvs/utvs/snow',
  //   'auto parts',
  // 'auto wheels & tires',
  //   'aviation',
  //   'baby+kids',
  //   'barter',
  //   'beauty+hlth',
  //   'bike parts',
  //   'bikes',
  //   'boat parts',
  //   'boats',
  //   'books',
  //   'business',
  'cars+trucks',
  //   'cds/dvd/vhs',
  'cell phones',
  //   'clothes+acc',
  //   'collectibles',
  'computer parts',
  'computers',
  'electronics',
  //   'farm+garden',
  'free stuff',
  'furniture',
  //   'garage sales',
  //   'general',
  //   'heavy equipment',
  'household',
  //   'jewelry',
  //   'materials',
  //   'motorcycle parts',
  //   'motorcycles',
  //   'music instr',
  //   'photo+video',
  //   'RVs',
  'sporting',
  //   'tickets',
  'tools',
  //   'toys+games',
  //   'trailers',
  'video gaming',
];

export const OWNER_TYPE = {
  ALL: 'All',
  OWNER: 'Owner',
  DEALER: 'Dealer',
};

// TODO: fill out all owner dealer codes
export const CATEGORY_CODES = {
  all: {owner: 'sso', dealer: 'ssq', all: 'sss', label: 'all'},
  antiques: {owner: 'atq', dealer: 'atd', all: 'ata', label: 'antiques'},
  appliances: {owner: 'app', dealer: 'ppd', all: 'ppa', label: 'appliances'},
  'arts+crafts': {owner: '', dealer: '', all: '', label: 'arts+crafts'},
  'atvs/utvs/snow': {owner: '', dealer: '', all: '', label: 'atvs/utvs/snow'},
  'auto parts': {owner: '', dealer: '', all: '', label: 'auto parts'},
  'auto wheels &amp; tires': {
    owner: '',
    dealer: '',
    all: '',
    label: 'auto wheels &amp; tires',
  },
  aviation: {owner: '', dealer: '', all: '', label: 'aviation'},
  'baby+kids': {owner: '', dealer: '', all: '', label: 'baby+kids'},
  barter: {owner: '', dealer: '', all: '', label: 'barter'},
  'beauty+hlth': {owner: '', dealer: '', all: '', label: 'beauty+hlth'},
  'bike parts': {owner: '', dealer: '', all: '', label: 'bike parts'},
  bikes: {owner: '', dealer: '', all: '', label: 'bikes'},
  'boat parts': {owner: '', dealer: '', all: '', label: 'boat parts'},
  boats: {owner: '', dealer: '', all: '', label: 'boats'},
  books: {owner: '', dealer: '', all: '', label: 'books'},
  business: {owner: '', dealer: '', all: '', label: 'business'},
  'cars+trucks': {
    owner: 'cto',
    dealer: 'ctd',
    all: 'cta',
    label: 'cars+trucks',
  },
  'cds/dvd/vhs': {owner: '', dealer: '', all: '', label: 'cds/dvd/vhs'},
  'cell phones': {
    owner: 'mob',
    dealer: 'mod',
    all: 'moa',
    label: 'cell phones',
  },
  'clothes+acc': {owner: '', dealer: '', all: '', label: 'clothes+acc'},
  collectibles: {owner: '', dealer: '', all: '', label: 'collectibles'},
  'computer parts': {
    owner: 'sop',
    dealer: 'sdp',
    all: 'syp',
    label: 'computer parts',
  },
  computers: {owner: 'sys', dealer: 'syd', all: 'sya', label: 'computers'},
  electronics: {owner: 'ele', dealer: 'eld', all: 'ela', label: 'electronics'},
  'farm+garden': {owner: '', dealer: '', all: '', label: 'farm+garden'},
  'free stuff': {owner: 'zip', dealer: 'zip', all: 'zip', label: 'free stuff'},
  furniture: {owner: 'fuo', dealer: 'fud', all: 'fua', label: 'furniture'},
  'garage sales': {owner: '', dealer: '', all: '', label: 'garage sales'},
  general: {owner: '', dealer: '', all: '', label: 'general'},
  'heavy equipment': {owner: '', dealer: '', all: '', label: 'heavy equipment'},
  household: {owner: 'hsh', dealer: 'hsd', all: 'hsa', label: 'household'},
  jewelry: {owner: '', dealer: '', all: '', label: 'jewelry'},
  materials: {owner: '', dealer: '', all: '', label: 'materials'},
  'motorcycle parts': {
    owner: '',
    dealer: '',
    all: '',
    label: 'motorcycle parts',
  },
  motorcycles: {owner: '', dealer: '', all: '', label: 'motorcycles'},
  'music instr': {owner: '', dealer: '', all: '', label: 'music instr'},
  'photo+video': {owner: '', dealer: '', all: '', label: 'photo+video'},
  RVs: {owner: '', dealer: '', all: '', label: 'RVs'},
  sporting: {owner: '', dealer: '', all: '', label: 'sporting'},
  tickets: {owner: '', dealer: '', all: '', label: 'tickets'},
  tools: {owner: '', dealer: '', all: '', label: 'tools'},
  'toys+games': {owner: '', dealer: '', all: '', label: 'toys+games'},
  trailers: {owner: '', dealer: '', all: '', label: 'trailers'},
  wanted: {owner: '', dealer: '', all: '', label: 'wanted'},
  'video gaming': {
    owner: 'vgm',
    dealer: 'vgd',
    all: 'vga',
    label: 'video gaming',
  },
};
